
-- TEST_OFFERING
insert into DS_EDU.TEST_OFFERING (NAME,DESCRIPTION,STATUS) values ('NAPLAN YEAR 3','NAPLAN YEAR 3','A');
insert into DS_EDU.TEST_OFFERING (NAME,DESCRIPTION,STATUS) values ('NAPLAN YEAR 5','NAPLAN YEAR 5','A');
insert into DS_EDU.TEST_OFFERING (NAME,DESCRIPTION,STATUS) values ('NAPLAN YEAR 7','NAPLAN YEAR 7','A');
insert into DS_EDU.TEST_OFFERING (NAME,DESCRIPTION,STATUS) values ('NAPLAN YEAR 9','NAPLAN YEAR 9','A');

insert into DS_EDU.TEST_OFFERING (NAME,DESCRIPTION,STATUS) values ('OPPORTUNITY CLASS PLACEMENT TEST','OPPORTUNITY CLASS PLACEMENT TEST','A');
insert into DS_EDU.TEST_OFFERING (NAME,DESCRIPTION,STATUS) values ('SELECTIVE HIGH SCHOOL PLACEMENT TEST','SELECTIVE HIGH SCHOOL PLACEMENT TEST','A');

commit;	
