
-- TEST_OFFERING
insert into DS_EDU.TEST_OFFERING (NAME,DESCRIPTION,STATUS) values ('NAPLAN YEAR 3','NAPLAN YEAR 3','A');
insert into DS_EDU.TEST_OFFERING (NAME,DESCRIPTION,STATUS) values ('NAPLAN YEAR 5','NAPLAN YEAR 5','A');
insert into DS_EDU.TEST_OFFERING (NAME,DESCRIPTION,STATUS) values ('NAPLAN YEAR 7','NAPLAN YEAR 7','A');
insert into DS_EDU.TEST_OFFERING (NAME,DESCRIPTION,STATUS) values ('OPPORTUNITY CLASS','OPPORTUNITY CLASS','A');
insert into DS_EDU.TEST_OFFERING (NAME,DESCRIPTION,STATUS) values ('SELECTIVE','SELECTIVE','A');

commit;	
